# Generated by Django 6.0.4 on 2026-04-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_break_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_work_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
