# Generated by Django 6.0.4 on 2026-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0002_alter_attendance_total_break_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
