# Generated by Django 6.0.4 on 2026-04-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0005_alter_attendance_total_break_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_break_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_work_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
