# Generated by Django 6.0.4 on 2026-04-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0006_alter_attendance_total_break_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_break_hours',
            field=models.CharField(default='0:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_work_hours',
            field=models.CharField(blank=True, default='0:00', max_length=10, null=True),
        ),
    ]
